### ISSUE TITLE
API route for messages by channel ID

### ISSUE THREAD

**Issue by burke1791** [orm-database/orm-database#41]
We have a route to get ALL messages.  I'm not sure of a use-case where that's helpful to the user, especially if they're downloading messages in DM channels that they aren't a part of.

Suggest refactoring the all messages route to get all messages in a specific channel.

**Comment by jlouie10** [comment]
Agreed. I have a question about API design. Would it be best practice to make a `GET /api/channels/:channel_id` request, where the response would be put together like:

```
{
  "channel_id": 1,
  "channel_name": "orm-database channel",
  "messages": [{
      "message_id": 23,
      "user_id": 4,
      "message_text": "LET'S GO!"
    },
    {
      "message_id": 24,
      "user_id": 4,
      "message_text": "Now"
    }
  ]
}
```

where the channel properties and any related objects are included in the response. So, in fact, we would not make a request like `GET /api/messages/:channel_id`. 

I think that the messages routes are all created as placeholders, since we had not gotten too far into it. We should review as a group at the start of class.

**Comment by burke1791** [comment]
For those looking at this after the fact, Justin's question was answered in a group discussion about the design.  We didn't ignore him.
